### PR TITLE
Make new wheel speicify they are arch dependent

### PR DESCRIPTION
**Pull request by nouiz**
See #71. This doesn't fix all released whl, only new one.

### CODE REVIEW

**Comment by Marvin182** [comment]
Our scripts failed to merge external PRs. We will fix that but in the meantime I merged this as #80. We will release a new wheel, latest Monday.

**Comment by nouiz** [comment]
Any update on the new wheel?

**Comment by jamesmyatt** [comment]
0.5.0 wheels look arch dependent: https://pypi.org/project/array-record/0.5.0/#files

**Comment by nouiz** [comment]
Yes. This is the fix.
Note, this doesn't solve complextly the issue on ARM, as pip check that the 0.5.0 is arch dependent and that there isn't a ARM wheel, so it skip it and looks at older one. And so he ends up installing 0.4.1.
To fully fix it, we should remove all previous wheel or redo them correctly or release an ARM wheel. In those fixes, I prefer the last one.

But now repo that depend on array_record can bump the min version to not install the old broken wheel on ARM:
https://github.com/tensorflow/datasets/pull/5109/
If you know more other repo that use array_record, it would be great to do the same on them.

**Pull request closed without merging**
